/* Writes the map hotspots into index.html from tools/map-spots.json.
   app/views/map.ejs reads the same file at render time, so this script exists
   only because the homepage is static HTML with no template behind it.

   The coordinates changed once already when the artwork was redrawn, and
   keeping two hand-edited copies in step was never going to survive a second
   redraw. Edit the JSON, run this, deploy index.html.

   Usage: node tools/build-map.js   */
const fs = require('fs'), path = require('path');

const ROOT = path.join(__dirname, '..');
const cfg = JSON.parse(fs.readFileSync(path.join(__dirname, 'map-spots.json'), 'utf8'));
const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const hotspots = cfg.spots.map(s =>
  `<a class="mapspot" href="${s.href}" style="left:${s.x}%;top:${s.y}%;width:${s.w}%;height:${s.h}%"` +
  ` aria-label="${esc(s.label)} — ${esc(s.sub)}">` +
  `<span class="mapspot__tip"><b>${esc(s.label)}</b><small>${esc(s.sub)}</small></span></a>`
).join('');

const block = `<!-- MAP:START — generated by tools/build-map.js from tools/map-spots.json.
     Do not edit the hotspots below by hand; edit the JSON and re-run it.
     The section hides itself if the artwork is not in place, so the homepage
     never shows a broken picture. -->
<section class="section section--parch2" id="shire"><div class="container">
<div class="bannerhead"><span class="eyebrow">&#9884; A Map of the Faire &#9884;</span><h2>Where Would You Like to Go?</h2><div class="rule"></div></div>
<p class="maplead">Press a place to walk in &mdash; or <a href="/map">see the map on its own page</a>.</p>
<div class="mapframe"><img class="mapart" src="${cfg.art}" width="${cfg.w}" height="${cfg.h}" loading="lazy" alt="An illustrated map of the House of Card and Coin: the House at its centre, with the Guild, the Tavern, the camp, the gallery and more around it." onerror="var s=document.getElementById('shire');if(s)s.style.display='none'">${hotspots}</div>
</div></section>
<!-- MAP:END -->`;

const file = path.join(ROOT, 'index.html');
let html = fs.readFileSync(file, 'utf8');
const start = html.indexOf('<!-- MAP:START');
const endTag = '<!-- MAP:END -->';
const end = html.indexOf(endTag);
if (start < 0 || end < 0) {
  console.error('FAILED: no MAP:START / MAP:END markers in index.html — not guessing where to put it.');
  process.exit(1);
}
html = html.slice(0, start) + block + html.slice(end + endTag.length);
fs.writeFileSync(file, html);

console.log('wrote ' + cfg.spots.length + ' hotspots into index.html');
cfg.spots.forEach(s => console.log('  ' + String(s.n).padStart(2) + '. ' +
  s.label.padEnd(20) + ' ' + (s.x + '%,' + s.y + '%').padEnd(14) + '-> ' + s.href));
