/* Writes the three day-columns of the Scroll of Events into events.html from
   tools/events.json. The server reads the same file to work out what is on
   next, so the page and the site cannot drift apart.

   Same arrangement as the map: one source of truth, one script, because
   events.html is static HTML with no template behind it.

   Usage: node tools/build-events.js   */
const fs = require('fs'), path = require('path');

const ROOT = path.join(__dirname, '..');
const cfg = JSON.parse(fs.readFileSync(path.join(__dirname, 'events.json'), 'utf8'));
const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const cols = cfg.days.map(d => {
  const mine = cfg.events.filter(e => e.date === d.date);
  const rows = mine.map(e =>
    `<div class="event"><span class="t">${esc(e.when)}</span>` +
    `<span class="b"><b>${esc(e.title)}</b><br>${esc(e.body)}</span></div>`
  ).join('');
  return `<div class="day"><div class="day__hd"><span class="d">${esc(d.name)}</span>` +
         `<span class="h">${esc(d.gates)}</span></div><div class="day__bd">${rows}</div></div>`;
}).join('');

const block = `<!-- EVENTS:START — generated by tools/build-events.js from tools/events.json.
     Do not edit the days below by hand; edit the JSON and re-run it. -->
<div class="grid grid--3">${cols}</div>
<!-- EVENTS:END -->`;

const file = path.join(ROOT, 'events.html');
let html = fs.readFileSync(file, 'utf8');

const start = html.indexOf('<!-- EVENTS:START');
const endTag = '<!-- EVENTS:END -->';
const end = html.indexOf(endTag);

if (start > -1 && end > -1) {
  html = html.slice(0, start) + block + html.slice(end + endTag.length);
} else {
  // First run: swap the hand-written grid for the generated one, matching only
  // the three-column grid that holds the days so nothing else is disturbed.
  // The hand-written grid is indented and broken across lines, so match
  // loosely from the opening tag to the close that follows the last day.
  const m = html.match(/<div class="grid grid--3">\s*<div class="day">[\s\S]*?<\/div><\/div><\/div>\s*<\/div>/);
  if (!m) { console.error('FAILED: could not find the day grid in events.html'); process.exit(1); }
  html = html.replace(m[0], block);
}

fs.writeFileSync(file, html);
console.log('wrote ' + cfg.events.length + ' events across ' + cfg.days.length + ' days into events.html');
cfg.days.forEach(d => {
  console.log('  ' + d.name);
  cfg.events.filter(e => e.date === d.date)
    .forEach(e => console.log('     ' + e.at + '  ' + e.when.padEnd(22) + e.title));
});
