/* Writes the map hotspots into index.html from tools/map-spots.json.
   app/views/map.ejs reads the same file at render time, so this script exists
   only because the homepage is static HTML with no template behind it.

   The coordinates changed once already when the artwork was redrawn, and
   keeping two hand-edited copies in step was never going to survive a second
   redraw. Edit the JSON, run this, deploy index.html.

   Usage: node tools/build-map.js   */
const fs = require('fs'), path = require('path');

const ROOT = path.join(__dirname, '..');
const cfg = JSON.parse(fs.readFileSync(path.join(__dirname, 'map-spots.json'), 'utf8'));
const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// The picture is stamped with its own modified time, so a redraw busts the
// cache and nothing else does.
let stamp = "";
try { stamp = '?v=' + Math.floor(fs.statSync(path.join(ROOT, String(cfg.art).replace(/^\//, ''))).mtimeMs); } catch (e) {}

/* Each hotspot carries its own slice of the map as a background, lined up
   exactly with the picture underneath. Invisible until hovered, when it lifts
   away with a white edge — a sticker peeled off the map. The arithmetic is the
   standard background-position percentage: an element w% wide shows the whole
   image at (100/w)% and the offset runs 0..100 across the remaining space. */
function slice(s) {
  const sz = `${(10000 / s.w).toFixed(2)}% ${(10000 / s.h).toFixed(2)}%`;
  const px = ((s.x - s.w / 2) / (100 - s.w) * 100).toFixed(3);
  const py = ((s.y - s.h / 2) / (100 - s.h) * 100).toFixed(3);
  return `background-image:url('${cfg.art}${stamp}');background-size:${sz};background-position:${px}% ${py}%;`;
}
const hotspots = cfg.spots.map(s =>
  `<a class="mapspot" href="${s.href}" style="left:${s.x}%;top:${s.y}%;width:${s.w}%;height:${s.h}%;${slice(s)}"` +
  ` aria-label="${esc(s.label)} — ${esc(s.sub)}">` +
  `<span class="mapspot__tip"><b>${esc(s.label)}</b><small>${esc(s.sub)}</small></span></a>`
).join('');

/* The ambient layer: firelight, lantern glow and a few embers laid over the
   painting. Light rather than objects — the picture already contains a fire
   and a pigeon, and drawing a second one on top would read as a mistake. */
const glows = (cfg.glow || []).map(g =>
  `<span class="mapglow mapglow--${g.kind}" style="left:${g.x}%;top:${g.y}%;width:${g.r * 2}%;padding-bottom:${g.r * 2}%"></span>`
).join('');

function emberSet(em, spread) {
  let out = '';
  for (let n = 0; n < ((em && em.count) || 0); n++) {
    const sway = ((n % 5) - 2) * spread;
    out += `<i class="mapember" style="left:${(em.x + sway).toFixed(2)}%;top:${em.y}%;` +
           `animation-delay:${(n * 0.34).toFixed(2)}s;animation-duration:${(2.6 + (n % 5) * 0.5).toFixed(1)}s"></i>`;
  }
  return out;
}
const embers = emberSet(cfg.embers, 0.55) + emberSet(cfg.embers2, 0.35);
const ambient = `<span class="mapfx" aria-hidden="true">${glows}${embers}</span>`;

const block = `<!-- MAP:START — generated by tools/build-map.js from tools/map-spots.json.
     Do not edit the hotspots below by hand; edit the JSON and re-run it.
     The section hides itself if the artwork is not in place, so the homepage
     never shows a broken picture. -->
<section class="section section--parch2" id="shire"><div class="container">
<div class="bannerhead"><h2>A Map of the House</h2><div class="rule"></div></div>
<p class="maplead">Press a place to walk in &mdash; or <a href="/map">see the map on its own page</a>.</p>
<div class="mapframe"><img class="mapart" src="${cfg.art}${stamp}" width="${cfg.w}" height="${cfg.h}" loading="lazy" alt="An illustrated map of this site drawn as a village: the House at its centre, with the Guild, the Tavern, the camp, the gallery and more around it." onerror="var s=document.getElementById('shire');if(s)s.style.display='none'">${ambient}${hotspots}</div>
</div></section>
<!-- MAP:END -->`;

const file = path.join(ROOT, 'index.html');
let html = fs.readFileSync(file, 'utf8');
const start = html.indexOf('<!-- MAP:START');
const endTag = '<!-- MAP:END -->';
const end = html.indexOf(endTag);
if (start < 0 || end < 0) {
  console.error('FAILED: no MAP:START / MAP:END markers in index.html — not guessing where to put it.');
  process.exit(1);
}
html = html.slice(0, start) + block + html.slice(end + endTag.length);
fs.writeFileSync(file, html);

console.log('wrote ' + cfg.spots.length + ' hotspots into index.html');
cfg.spots.forEach(s => console.log('  ' + String(s.n).padStart(2) + '. ' +
  s.label.padEnd(20) + ' ' + (s.x + '%,' + s.y + '%').padEnd(14) + '-> ' + s.href));
